name: 'Renovate Automatic Branch'
description: 'Automatically create an empty branch to merge Renovate PR.'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  # CREDENTIALS
  github-token:
    description: 'Github Token'
    required: true
    default: ${{ github.token }}
  repo-owner:
    description: 'Repo Owner (the name of the org or user in the URL)'
    required: true
  repo-name:
    description: 'Repo Name'
    required: true
  branch-to-create:
    description: 'The name of the branch that will be created'
    required: false
    default: 'chore/renovateBaseBranch'
  branch-base:
    description: 'The name of the branch that will be used as base'
    required: false
    default: 'main'
  empty-commit-msg:
    description: 'The commit msg that will be created by the script'
    required: false
    default: 'chore: automatic empty commit'
  pull-request-title:
    description: 'The PR title'
    required: false
    default: 'fix: dependencies'
  pull-request-body:
    description: 'The body (description) of the pull request opened by the action'
    required: false
    default: 'Weekly dependencies update.'

runs:
  using: 'node20'
  main: 'dist-ga/index.js'
